namespace Orchestrator.Domain.StateMachines;

public enum BusinessStatus
{
    CREATED, DOCUMENT_RECEIVED, VALIDATING, READY_FOR_SIGNATURE, SIGNATURE_IN_PROGRESS,
    PARTIALLY_SIGNED, SIGNED, FINALIZING, COMPLETED,
    FAILED, CANCELLED, EXPIRED, REJECTED
}

public enum OperationalStatus { READY, PROCESSING, RETRY_PENDING, SUSPENDED, DLQ, MANUAL_ACTION }

public enum OperationStatus { NOT_STARTED, PROCESSING, RETRY_PENDING, DLQ, COMPLETED, FAILED, CANCELLED }

public enum ErrorClass { TRANSIENT, PERMANENT, UNKNOWN }

public enum OperationType
{
    DOCUMENT_DOWNLOAD, DOCUMENT_STORE, IDENTITY_VALIDATION, PROVIDER_CREATE_PROCESS, PROVIDER_SEND_DOCUMENT,
    PROVIDER_STATUS_CHECK, SIGNED_DOCUMENT_DOWNLOAD, SIGNED_DOCUMENT_STORE, CALLBACK_SEND, OUTPUT_DELIVERY,
    CONFIRMATION_SEND, CONFIRMATION_VERIFY
}

public enum ConfirmationStatus { PLANNED, SENDING, SENT, CONFIRMED, LOCKED }
